version: "3"
services:
  kafka:
    image: krisgeus/docker-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://localhost:9093"
      LISTENERS: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093"
      SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
      INTER_BROKER: "INTERNAL"
      KAFKA_CREATE_TOPICS: "example_topic:2:1"
